obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[-0.210, -0.210], [-0.210, 0.210], [0.082, 0.210], [0.082, -0.210]]
# footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
# inflation_radius: 0.3

# plugins: 
#     - {name: static_layer,        type: "costmap_2d::StaticLayer"}
#     - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
#     - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
#     # - {name: social_layer,        type: "social_navigation_layers::ProxemicLayer"}
#     # - {name: social_pass_layer,   type: "social_navigation_layers::PassingLayer"}

# static_layer:
#     enabled: true
#     map_topic: "/map"

# inflation_layer:
#     enabled: true
#     cost_scaling_factor: 5
#     inflation_radius: 0.55

# obstacle_layer:
#     observation_sources: scan
#     footprint_clearing_enabled: true
#     scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
  
# # social_layer:
# #     enabled: true
# #     cutoff: 10.0
# #     amplitude: 77.0
# #     covariance: 0.25
# #     factor: 5.0
# #     keep_time: 0.75
      