obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[-0.210, -0.210], [-0.210, 0.210], [0.082, 0.210], [0.082, -0.210]]
plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

